name: Build docker image

on:
  schedule:
  - cron: "0 0 * * 1" # Run on Monday at 00:00
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        repository: zekker6/protractor-headless
        context: .
        push: true
