name: Build docker image

on:
  schedule:
  - cron: "0 0 * * 1" # Run on Monday at 00:00
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: zekker6/protractor-headless
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: Dockerfile