name: Build docker image

permissions:
  contents: write
  packages: write

on:
  schedule:
  - cron: "0 0 * * 1" # Run on Monday at 00:00
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        tags: zekker6/protractor-headless:latest, ghcr.io/${{ github.repository }}
        context: .
        push: true
